### PR TITLE
Get the seeder working again: protocol 70029, dead bootstrap lists, glibc 2.38 build

### PR DESCRIPTION
**Pull request by ohcee**
This crawler hasn't been able to reach a Veil node since May 2021, and on anything current it doesn't even compile. All of it turned out to be small stuff. With these fixes it runs, and a live deployment has been serving `seed.veil-info.org` since 2026-08-07.

**1. Protocol version (`serialize.h`)**

`PROTOCOL_VERSION` was 70028. Veil enforces a minimum peer version of 70029 once the chain passes `nTimeKIfork` (1621180800, so 2021-05-16). Since that date every node answers a 70028 `version` message with

```
reject: version ... Version must be 70029 or greater
```

and hangs up. I checked against live mainnet nodes: 70028 gets rejected and disconnected, 70029 handshakes and gets `verack`. The last commit here is from November 2020, so this killed the seeder about six months after it was last touched, and there's no way to tell from the outside. I added a comment saying the value has to track the node's `MIN_PEER_PROTO_VERSION_AFTER_ENFORCEMENT`, since that's not obvious to anyone reading it later.

**2. Won't build on glibc 2.38 or newer (`strlcpy.h`)**

glibc grew its own `strlcpy` and `strlcat` in 2.38, so the bundled inline copies are now a redeclaration of something the C library already defines:

```
strlcpy.h:49:15: error: 'size_t strlcpy(char*, const char*, size_t)'
redeclared inline without 'gnu_inline' attribute
```

Ubuntu 24.04 ships glibc 2.39, so this hasn't built on a current distro for roughly two years. Now it only defines them where the C library doesn't.

**3. Bootstrap lists (`main.cpp`)**

Not one entry in either list reaches a node any more. Checked today:

- `node03.veil-project.com` is the only hostname that gets you to a live node
- `node01`, `node02` and `node04` resolve but the P2P port is closed. `node01` answers with a Cloudflare proxy address, which can't carry P2P at all
- `node05` through `node08` have no DNS record
- `veilseed.veil-stats.com` and `seed.veil.rune.network` are NXDOMAIN, and `veil-seed.pontificatingnobody.com`'s nameservers don't answer
- all eight hardcoded 2019 era addresses refuse or time out on 58810

Testnet is the same story with nothing left standing at all.

So the crawler starts with a single usable bootstrap address, and if node03 is having a bad day, none. Replaced with nodes verified by full `version`/`verack` handshake, the same set proposed as fixed seeds in Veil-Project/veil, plus the one reachable testnet node.

**4. Empty database crash (already on the `updates` branch)**

`CAddrDb::GetStats` read `ourId[0]` to work out the last attempt age. `ourId` is an empty `std::deque` until the first node has been tried, which is the state of every fresh deployment, so the stats thread indexed out of bounds and took the process down with SIGSEGV about a second after startup. I hit this while testing and can confirm the `updates` commits already in this branch fix it. They also guard the null `dnsThread` entries during the startup race.

**5. Build and docs**

The Makefile hardcoded `g++` and there was no way to add an include path without replacing `CXXFLAGS` wholesale, which breaks any host keeping Boost or OpenSSL outside the default prefix. It now honours `CXX`, `CPPFLAGS` and `LDFLAGS`, defaults unchanged, so plain `make` on Debian behaves exactly as before.

README got everything a real deployment turned out to need, most of which was folklore before: the NS delegation is the record that matters and a plain A record on the seed name does nothing, providers commonly filter inbound UDP 53 and have to be asked, the port redirect is the right call on systemd hosts because taking `0.0.0.0:53` collides with systemd-resolved and disabling its stub listener breaks resolution for everything else on the box, and the first crawl reports nothing for several minutes because results are only recorded once a thread finishes its whole batch, which looks exactly like a hang. Also a systemd unit in `contrib/`.

**Running**

Deployed on a VPS behind an NS delegation, first full pass:

```
9/53 available (53 tried in 881s, 0 new, 0 active), 0 banned
```

and answering publicly:

```
$ dig +short seed.veil-info.org
169.58.67.195
62.72.43.203
209.126.9.235
57.131.32.128
```

Different subset per query, as it should be. One of the nodes it turned up through `getaddr` (`109.123.233.94`) wasn't in any hand built list, which is the whole point of running a crawler instead of maintaining a text file.

**Why bother now**

Veil-Project/veil currently has one working DNS seed out of fourteen, and the compiled in fixed seeds are still Bitcoin v0.17's list on port 8333, so that fallback has never worked. There's a PR fixing the static side of that. This is the part that keeps it fixed, since a seed list is a photograph and a crawler is a live feed.

Not covered here: it's single instance with no HA, and the DNS threads can't share a port on macOS, though Linux is fine.

### CODE REVIEW

File: main.cpp
Comment (Veil-Project) [inline main.cpp:1]: We may as well take out node03.veil-project.com too, as it is also listed in your IPv4 numbered addresses below. Likewise, node01 (block explorer), which because it is proxied through CloudFlare doesn't respond as it doesn't expose the P2P ports on the proxy addresses, is actually also listed numerically below. Some others of the listed nodes will be in the same case.

**Review by Veil-Project — CHANGES_REQUESTED** [review]
This is good. `node03.veil-project.com` should also be removed as it is duplicated by IP address in the numeric addresses below, as the DNS identification is unnecessary.

Regarding testnet, the testnet explorer was closed down in April 2026 for cost-saving, along with the EU and US snapshot servers. This is likely to happen to the mainnet snapshot servers since their recent functional replacement. So we'll get the seeder onto some other nodes, not necessarily labelled by DNS as a centralised node, as they are being decentralised, and decentralised operators might submit addresses at a later time.

**Review by Veil-Project — APPROVED** [review]
It's all good.
